### ISSUE TITLE
Feature request: Flow types generator

### ISSUE THREAD

**Issue by schickling** [prismagraphql/prisma-binding#154]
Right now the `prisma-binding` generator just supports `javascript` + `typescript`. It would be great if someone would be open to contribute support for flow types.

**Comment by medelman17** [comment]
I'll take a crack at this.

**Comment by medelman17** [comment]
This issue may be closed.

**Comment by marktani** [comment]
Thanks for the PR https://github.com/prismagraphql/prisma-binding/pull/170 @medelman17 🙏
