### ISSUE TITLE
Aliases are not resolved correctly 

### ISSUE THREAD

**Issue by lewisblackwood** [prismagraphql/prisma-binding#176]
This bug report is based on [this thread](https://prisma.slack.com/archives/CA491RJH0/p1527165251000011) in the Prisma slack channel.

I'm using `prisma-binding` with a `graphql-yoga` app. In some cases, aliases are incorrectly resolved as null. For example, this query:

```javascript
query {
  currentUser {
    organisation {
      usersWithInvite: users(
        where: { invite: { id_not: null } }
      ) {
        id
      }
    }
  }
}
```

returns:

```javascript
{
  "data": {
    "currentUser": {
      "organisation": {
        "usersWithInvite": null
      }
    }
  }
}
```

If I add another `users` subselection to the query, the alias will be resolved correctly:

```javascript
{
  "data": {
    "currentUser": {
      "organisation": {
        "users": [
          ...manyUsers
        ],
        "usersWithInvite": [
           ...manyUsers
        ]
      }
    }
  }
}
```

If I look at the logs of the running Yoga server, I can see that data is retrieved for the alias I've used:

```javascript
Response from http://localhost:4466:
{
  "user": {
    "organisation": {
      "usersWithInvite": [
        {
          "id": "cjhj6fv4403vu0820bavvaw97"
        }
      ]
    }
  }
}
```

**Comment by schickling** [comment]
@timsuchanek can you please provide an example on how to use GraphQL/Prisma bindings in combination with aliases?

@nikolasburk please make sure to add this special case regarding aliases to the docs.

**Comment by divyenduz** [comment]
Hi @lewisblackwood, thanks for raising this issue! 

Can you please confirm that if you are using `tracing` or `cacheControl` option while starting the `graphql-yoga` server? 

As @timsuchanek suggested in the thread, we had [deployed a fix](https://github.com/prismagraphql/graphql-yoga/pull/216) for this but [that does not work is `tracing` or `cacheControl` options](https://github.com/apollographql/apollo-server/issues/865) are enabled and [`tracing` is enabled](https://github.com/prismagraphql/graphql-yoga#startoptions-options-callback-options-options--void----null-promisevoid) by default with latest version of graphql-yoga - raising a separate issue to see if we need to change that. 

For more details and a workaround, please refer to [this comment](https://github.com/prismagraphql/prisma/issues/2429#issuecomment-392253774)

Thanks!

**Comment by lewisblackwood** [comment]
Thanks for the reply @divyenduz. I disabled tracing and that did indeed fix the issue with aliases 👍
