### ISSUE TITLE
prisma.request Promise returns undefined on error

### ISSUE THREAD

**Issue by terion-name** [prismagraphql/prisma-binding#182]
**upd**
More generalizing the issue — on any error prisma.reqest Promise silently returns undefined and it is simply impossible to debug anything. A huge, huge problem

A resolver:
```js
import {
  ArticleFlatFragment,
  ArticleTranslationFlatFragment,
  TagFlatFragment,
  TagLabelFlatFragment,
  TypeFlatFragment,
  TypeLabelFlatFragment
} from "../../schema/generated/mysql.fragments"; // fragments are generated by my own

const fragments = {
  ArticleFlatFragment,
  ArticleTranslationFlatFragment,
  TagFlatFragment,
  TagLabelFlatFragment,
  TypeFlatFragment,
  TypeLabelFlatFragment
};

export const articleReturn = `{
  ...ArticleFlat 
  translations(where: {lang: $lang}, first: 1) { ...ArticleTranslationFlat }
  type ${require('../type/typesLocalized.resolvers').typeReturn}
  tags ${require('../tag/tagsLocalized.resolvers').tagReturn}
}`;

export async function articlesLocalized(_, args, ctx, info) {
  const req = `query($lang: String!) { 
    articles ${articleReturn} 
  }
  ${Object.values(fragments).join('\n')}
  `;
  console.log(req);
  const result = await ctx.prisma.request(req, {lang: ctx.lang}); // Prisma instance is injected `prisma` ctx property
  console.log(result);
  return result.map(entry => collapseArticle(entry));
}
```

`result` is undefined. 

I copy from console entire request, run it directly over prisma server and it works:

<img width="1450" alt="2018-06-02 19 28 47" src="https://user-images.githubusercontent.com/1060205/40878522-317908fc-669b-11e8-83d8-1f1313205230.png">

**Comment by terion-name** [comment]
Ok, after fixing fragments (see https://github.com/prismagraphql/graphql-request/issues/86) it began to work.

BUT!

The issue is still present: the Promise should be rejecting on query error and messaging what was wrong, not just silently return undefined

**Comment by marktani** [comment]
Can you provide a reproduction for this behaviour? 🙂

**Comment by terion-name** [comment]
@marktani in what form? a repo? is there a sort of template for this?

in any case just run `await ctx.db. request('query { anyMalformedQuery() {} }')` — that's all reproduction. You'll get `undefined`

**Comment by marktani** [comment]
Awesome, that's already enough. Thanks! 🙂

**Comment by marktani** [comment]
Hey @terion-name, we were focusing on the GraphQL Europe conference lately and haven't started to investigate this yet (the conference was amazing by the way!)

Did you consider providing a PR? :slightly_smiling_face:

**Comment by terion-name** [comment]
@marktani I'd be happy, but I'm not so confident in your source code. As far as I understand you use for this `graphql-request`, and issue is common for `prisma-binding` and for generic `graphql-binding` (faced it yesterday). So it seems to be problem in GraphQLClient... Well, I'll try to figure this out and make a PR if succeed

**Comment by divyenduz** [comment]
Currently, we pluck [the data](https://github.com/graphql-binding/graphql-binding/blob/8ce6a0129d7ce3a96fd0044b6857366dfa005654/src/Delegate.ts#L42-L44) out of response and consume the error. Even showing this error via any will display only the schema side error. 

There is already a [broad proposal](https://github.com/prismagraphql/prisma/issues/2199) to get around this issue that needs further discussion.
