### ISSUE TITLE
Bug in graphql-tools 3.0.1 - update to latest 3.0.3

### ISSUE THREAD

**Issue by develomark** [prismagraphql/prisma-binding#195]
There is a bug in `graphql-tools` that has been fixed in `3.0.2`+ renders fragments in the query fairly broken.

https://github.com/apollographql/graphql-tools/issues/777

There are also a number of additional bug fixes added in `3.0.3`.

Please upgrade to latest (also consider changing package.json version to `"graphql-tools": "^3.0.3"` - so we can get latest updates easier.

Many thanks.

**Comment by marktani** [comment]
Thanks for the suggestion, @develomark - we will investigate and resolve [the merge conflict](https://github.com/prismagraphql/prisma-binding/pull/173) for our renovate automation around this workflow soon 🙂

**Comment by develomark** [comment]
Thanks!

**Comment by divyenduz** [comment]
This was released in [2.1.1](https://github.com/prismagraphql/prisma-binding/releases) 🎉
