### ISSUE TITLE
Implicitly inserting null values for mutations

### ISSUE THREAD

**Issue by mellogarrett** [prismagraphql/prisma-binding#201]
I have a `services` database table (Postgres) with a `NOT NULL` constraint on one field; `created_at`.

When I use the `ctx.prisma.mutation.createService` prisma binding, it automatically adds `null` for each value that I don't specify, which breaks the aforementioned not-null constraint.

So when I run this:
```js
ctx.prisma.mutation.createService({
  service_name: "test",
  status: "On",
  user: "abc123"
}, info)
```
it throws this error: 
<img width="664" alt="screen shot 2018-07-10 at 2 11 14 pm" src="https://user-images.githubusercontent.com/9908831/42529484-9a7cce5a-844c-11e8-8d10-b70dffed422c.png">
The second to the last `null` is where the `created_at` column is

**Comment by marktani** [comment]
Issue moved to [prismagraphql/prisma #2755](https://github.com/prismagraphql/prisma/issues/2755) via [**ZenHub**](https://www.zenhub.com/)
