### ISSUE TITLE
Cannot use date before 1970-01-01

### ISSUE THREAD

**Issue by jon-ht** [prismagraphql/prisma-binding#203]
Hi,

It seems that's not possible to use a datetime before 1970-01-01.

Here is my simplified request :

```gql
mutation {
  createPerson(
    data: {
      dateOfBirth: "1969-01-01T10:33:59.828Z"
    }
  ) {
    id
    dateOfBirth
  }
}
```

```json
{
  "data": {
    "createPerson": null
  },
  "errors": [
    {
      "message": "Whoops. Looks like an internal server error. Search your server logs for request ID: local:api:cjjiw6k85002k076838g1qn78",
      "locations": [],
      "path": [
        "createDefunct"
      ],
      "requestId": "local:api:cjjiw6k85002k076838g1qn78"
    }
  ]
}
```

If I change datetime value by `1970-01-01T10:33:59.828Z`, it works as expected

**Comment by marktani** [comment]
Issue moved to [prismagraphql/prisma #2768](https://github.com/prismagraphql/prisma/issues/2768) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jon-ht** [comment]
Sorry, I didn't know where to post, thanks for your intervention !

**Comment by marktani** [comment]
Sure, no worries 🙂
