### ISSUE TITLE
Calling a variable "data" breaks mutation

### ISSUE THREAD

**Issue by michaelchiche** [prismagraphql/prisma-binding#73]
You can find a see the bug using this repository: https://github.com/michaelchiche/prisma-variable-name-data

then running these two mutations: 

```graphql
mutation Works($post: PostCreateWithoutAuthorInput!) {
  createPostOK(post: $post) {
    id
  }
}

mutation Fails($post: PostCreateWithoutAuthorInput!) {
  createPostKO(data: $post) {
    id
  }
}
```

with this data for post:

```json
{
  "post": {
    "title": "OK",
    "text": "I work fine with post",
    "isPublished": false
  }
}
```

and both mutations call this function: 

```ts
function createPost(
  parent,
  post: PostCreateWithoutAuthorInput,
  context: Context,
  info,
) {
  const p: PostCreateInput = {
    ...post,
    author: {
      connect: {
        slug: 'michael',
      },
    },
  };
  return context.db.mutation.createPost({ data: p }, info);
}
```

**Comment by marktani** [comment]
Thanks for the report @michaelchiche!

I propose either of the following changes:

* support calling a variable `data` (or `where` [for other cases](https://github.com/graphql-boilerplates/node-graphql-server/issues/109)) - generally all variable names should be allowed
* or, if that is not possible for whatever reason, a friendly, precise and helpful error message should be shown in the logs that warns the developer and asks them to rename their variable

**Comment by KATT** [comment]
My workaround was to using `input` instead of `data` as the convention in my API Gateway. 

Would be nice to fix though, I try to follow the conventions of Prisma in my API Gateway to simplify dev experience

**Comment by marktani** [comment]
I believe this is rooted in a bug in [graphql-tools](https://github.com/apollographql/graphql-tools/), but haven't had the chance to verify yet. If anyone wants to take a stab at looking closer into this, let me know 🙌

**Comment by anonymous-coder** [comment]
not sure why im getting: 

    Error: Variable "$_where" got invalid value {"facebookUserId":"xxxxxxxxxx"}; Field 
    "facebookUserId" is not defined by type UserWhereUniqueInput.

on this: 

     async function facebookUser(parent, { facebookToken }, context, info) {
     let user = null
     try {
       const facebookUser = await getFacebookUser(facebookToken)
       user = await context.db.query.user(
        { where: { facebookUserId: facebookUser.id } },
        info,
       )
       if (!user) {
         user = await createUserFromFacebook(context, facebookUser)
       }
       return {
         token: jwt.sign({ userId: user.id }, APP_SECRET),
         user,
       }
     } catch (error) {
       throw new Error(error)
     }
    }

Ive defined facebookUserId on my User Type
sorry if im missing something simple, long week

**Comment by marktani** [comment]
Hey @anonymous-coder, thanks for sharing your problem here 🙂 I believe I sent you here by mistake, now looking at your question again.

It looks like the field `facebookUserId` is missing the `@unique` directive in your datamodel.
Can you add it, then deploy again? This should make the `facebookUserId` argument available for the [unique where selection](https://www.prismagraphql.com/docs/reference/prisma-api/concepts-utee3eiquo#node-selection).

Here's an example:

```diff
type User {
  id: ID! @unique
  name: String!
- facebookUserId: String!
+ facebookUserId: String! @unique
}
```

If that's not your issue, then additonally share your application schema `schema.graphql` 🙂

**Comment by anonymous-coder** [comment]
whenever i put @unique i get this error: 

                 throw new Error("Directive " + directiveName + ": Couldn't find type " + directiveName + " 
        in any of the schemas.");
                ^

     Error: Directive unique: Couldn't find type unique in any of the schemas.

this was a issue i had with just the Id field.

    # import Post from "./generated/prisma.graphql"

     type Query {
       feed(filter: String, skip: Int, first: Int, orderBy: PostOrderByInput): Feed!
      loggedInUser: loggedInUserPayload!
      post(id: ID!): Post!
     me: User
    }

    type Feed {
      posts: [Post!]!
      count: Int!
    }

    type Mutation {
      signup(email: String!, password: String!, firstName: String!, gender: String,  birthday: String): 
     AuthPayload
      login(email: String!, password: String!): AuthPayload
      facebookUser(facebookToken: String!): FacebookUserPayload
      post(title: String!, description: String!, preference: String, tags: String): Post!
      deletePost(id: ID!): Post!
      publish(id: ID!): Post!
     }

    type AuthPayload {
      token: String
      user: User
    }

    type FacebookUserPayload {
      token: String!
    }

    type loggedInUserPayload {
      id: ID!
    }

      type User {
        id: ID!  @unique
        facebookUserId: String! 
        email: String!
        firstName: String!
        lastName: String
        gender: String!
        birthday: String!
        locale: String
        picture: String
        posts: [Post!]!
       }

    type Subscription {
      newPost: PostSubscriptionPayload
    }

**Comment by marktani** [comment]
You need to add `@unique` to your *datamodel*, which is often called `prisma.graphql`, or `types.graphql`, not your *application schema*, which is often called `schema.graphql` 🙂

**Comment by schickling** [comment]
Thanks a lot @divyenduz and @timsuchanek for digging into this. Looking forward to a fix @freiksenet! 🎉

**Comment by k00k** [comment]
Just to confirm, this does happen with `where` as well. For example, when trying to compound a `where` clause in a resolver, this compounded `where` in the resolver is completely ignored:

`return context.db.query.games({ where: { AND: [{ active: true }, { ...args.where }] } }, info)`

**Comment by nathanforce** [comment]
To chime in here, I am seeing the same with a variable called `after`. If I change the variable to `afterDate` then all works fine.

```
    posts: async (
      parent,
      { author, first, after },
      context: Context,
      info
    ) => {
      return context.db.query.posts(
        {
          where: {
            author: { id: author },
            time: { start_gte: after },
          },
          first,
        },
        info
      );
    },
```
